version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:23"
      timezone: "Europe/Bucharest"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "ci"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "05:23"
      timezone: "Europe/Bucharest"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
    groups:
      production-minor-patch:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      development-minor-patch:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "build"
