# Generated by Django 5.1.4 on 2026-04-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='module',
            field=models.CharField(choices=[('module1', 'Module 1 — Fundamentals'), ('module2', 'Module 2 — Control Flow'), ('module3', 'Module 3 — Data Collections'), ('module4', 'Module 4 — Functions & Exceptions')], db_index=True, default='module1', help_text='PCEP-30-02 syllabus module this question belongs to.', max_length=16),
        ),
    ]
