"""
PCEP question bank for the seed_questions management command.

Coverage (PCEP-30-02 syllabus):
- Module 1 — Computer Programming and Python Fundamentals
- Module 2 — Control Flow (conditionals and loops)
- Module 3 — Data Collections (lists, tuples, dicts, strings)
- Module 4 — Functions and Exceptions

Each question has 4 choices. The `explanation` field on every choice should
answer WHY: correct choices explain the Python rule at play; wrong choices
explain the specific misconception they tempt the reader into.
"""

# ---------------------------------------------------------------------------
# MODULE 1 — COMPUTER PROGRAMMING AND PYTHON FUNDAMENTALS
# ---------------------------------------------------------------------------

MODULE_1 = [
    {
        'text': 'What is the output?',
        'code_snippet': 'print(5 / 2)',
        'difficulty': 'easy',
        'choices': [
            {'text': '2', 'is_correct': False,
             'explanation': 'Wrong. The single slash `/` is TRUE division in Python 3; it always returns a float. For integer-truncating division use `//` (floor division).'},
            {'text': '2.5', 'is_correct': True,
             'explanation': 'Correct. In Python 3, `/` is true division and always produces a float, even when both operands are integers. `5 / 2` is `2.5`.'},
            {'text': '2.0', 'is_correct': False,
             'explanation': 'Wrong. True division of `5 / 2` produces `2.5`, not `2.0`. You may be confusing it with `4 / 2` (which would be `2.0`).'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. Dividing two integers is a perfectly valid operation and raises no exception.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': 'print(7 // 2)',
        'difficulty': 'easy',
        'choices': [
            {'text': '3.5', 'is_correct': False,
             'explanation': 'Wrong. The double slash `//` is FLOOR division. It discards the fractional part. You\'re thinking of `/` (true division).'},
            {'text': '3', 'is_correct': True,
             'explanation': 'Correct. `//` performs floor division: it returns the quotient rounded DOWN. With two ints it returns an int. `7 // 2 == 3`.'},
            {'text': '4', 'is_correct': False,
             'explanation': 'Wrong. Floor division rounds TOWARD NEGATIVE INFINITY, not up. For positive numbers that means truncation, so `7 // 2` is 3, not 4.'},
            {'text': '3.0', 'is_correct': False,
             'explanation': 'Wrong. When both operands of `//` are integers, the result is also an integer (no decimal point). `7.0 // 2` would give `3.0`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': 'print(17 % 5)',
        'difficulty': 'easy',
        'choices': [
            {'text': '3', 'is_correct': False,
             'explanation': 'Wrong. The modulo operator returns the REMAINDER, not the quotient. `17 // 5 == 3` is the quotient; the remainder is `17 - 3*5 = 2`.'},
            {'text': '2', 'is_correct': True,
             'explanation': 'Correct. `%` is the modulo (remainder) operator. `17 = 3*5 + 2`, so `17 % 5` is 2.'},
            {'text': '3.4', 'is_correct': False,
             'explanation': 'Wrong. `%` returns the integer remainder, not the fractional quotient. You seem to be computing `17 / 5`, which is a different operator.'},
            {'text': '0', 'is_correct': False,
             'explanation': 'Wrong. `17 % 5` would only be 0 if 5 divided 17 evenly, which it does not. The remainder is 2.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': 'print(2 ** 3 ** 2)',
        'difficulty': 'medium',
        'choices': [
            {'text': '64', 'is_correct': False,
             'explanation': 'Wrong. This would be the answer if `**` were LEFT-associative: `(2**3)**2 = 8**2 = 64`. But exponentiation in Python is RIGHT-associative.'},
            {'text': '512', 'is_correct': True,
             'explanation': 'Correct. Unlike most binary operators, `**` is right-associative: `2 ** 3 ** 2` is parsed as `2 ** (3 ** 2)` = `2 ** 9` = 512.'},
            {'text': '36', 'is_correct': False,
             'explanation': 'Wrong. This would be `(2 * 3) ** 2`, but `**` is exponentiation, not multiplication.'},
            {'text': '256', 'is_correct': False,
             'explanation': 'Wrong. 256 = 2 ** 8, but the exponent here is `3 ** 2 = 9`, so the result is `2 ** 9 = 512`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "print('ab' * 3)",
        'difficulty': 'easy',
        'choices': [
            {'text': 'ababab', 'is_correct': True,
             'explanation': 'Correct. The `*` operator between a string and a non-negative integer produces the string repeated that many times. `\'ab\' * 3 == \'ababab\'`.'},
            {'text': 'ab * 3', 'is_correct': False,
             'explanation': 'Wrong. `print` evaluates its argument first; the expression `\'ab\' * 3` is computed (string repetition) BEFORE printing, producing `\'ababab\'`.'},
            {'text': "['ab', 'ab', 'ab']", 'is_correct': False,
             'explanation': 'Wrong. Multiplying a STRING by an integer concatenates copies into a single string. Multiplying a LIST `[\'ab\'] * 3` would give `[\'ab\', \'ab\', \'ab\']`.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `str * int` is a perfectly valid operation in Python — it\'s documented string repetition. TypeError would be raised for `str * str` or `str * float`.'},
        ],
    },
    {
        'text': 'What happens when this runs?',
        'code_snippet': "print('abc' + 3)",
        'difficulty': 'easy',
        'choices': [
            {'text': 'abc3', 'is_correct': False,
             'explanation': 'Wrong. Python does NOT auto-convert between `str` and `int` for the `+` operator. To get this output you\'d need `\'abc\' + str(3)` or an f-string `f\'abc{3}\'`.'},
            {'text': 'TypeError', 'is_correct': True,
             'explanation': 'Correct. `+` requires operands of compatible types. `str + str` concatenates, `int + int` adds, but `str + int` raises `TypeError: can only concatenate str (not "int") to str`.'},
            {'text': 'abcabcabc', 'is_correct': False,
             'explanation': 'Wrong. That would be `\'abc\' * 3` (repetition). With `+` the operand types must match.'},
            {'text': '6', 'is_correct': False,
             'explanation': 'Wrong. Python does not sum character codes — and even if it did, this expression never reaches that point because of the type mismatch.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "print('a', 'b', 'c', sep='-')",
        'difficulty': 'easy',
        'choices': [
            {'text': 'a b c', 'is_correct': False,
             'explanation': 'Wrong. A space separator is the DEFAULT (`sep=\' \'`), but here `sep=\'-\'` is explicit.'},
            {'text': 'a-b-c', 'is_correct': True,
             'explanation': 'Correct. `print` joins its positional arguments with the value of `sep`, which defaults to a space but was set to `\'-\'` here.'},
            {'text': 'abc', 'is_correct': False,
             'explanation': 'Wrong. `sep=\'\'` (empty string) would produce `abc`. Here `sep=\'-\'` inserts a dash between each argument.'},
            {'text': "a,b,c-", 'is_correct': False,
             'explanation': 'Wrong. `sep` goes only BETWEEN arguments, not after the last one. And the separator here is `-`, not `,`.'},
        ],
    },
    {
        'text': 'What is printed?',
        'code_snippet': "print('hi', end='!')\nprint('bye')",
        'difficulty': 'easy',
        'choices': [
            {'text': 'hi\\nbye', 'is_correct': False,
             'explanation': 'Wrong. `end` replaces the DEFAULT newline at the end of `print`. With `end=\'!\'`, no newline is emitted after `hi`.'},
            {'text': 'hi!bye', 'is_correct': True,
             'explanation': 'Correct. `end` is the string appended after all arguments instead of the default `\\n`. So the first print emits `hi!` without a newline, then `bye\\n` follows on the same line.'},
            {'text': 'hi!\\nbye', 'is_correct': False,
             'explanation': 'Wrong. `end=\'!\'` REPLACES the default newline; it does not add the `!` before it. No newline is emitted after `hi!`.'},
            {'text': 'hibye', 'is_correct': False,
             'explanation': 'Wrong. `end=\'!\'` inserts `!`, not nothing. For no separator you would write `end=\'\'`.'},
        ],
    },
    {
        'text': 'Which type does `3 / 2` evaluate to?',
        'code_snippet': '',
        'difficulty': 'easy',
        'choices': [
            {'text': 'int', 'is_correct': False,
             'explanation': 'Wrong. In Python 3, `/` always returns a float, even when both operands divide evenly. Python 2 used to return int for int/int, but that was removed.'},
            {'text': 'float', 'is_correct': True,
             'explanation': 'Correct. In Python 3, `/` (true division) always returns `float`, regardless of operand types. `3 / 2` is `1.5`.'},
            {'text': 'complex', 'is_correct': False,
             'explanation': 'Wrong. `complex` results come from operations involving complex numbers (written with `j`, e.g. `3 + 2j`). Division of two real ints gives `float`.'},
            {'text': 'bool', 'is_correct': False,
             'explanation': 'Wrong. `bool` is returned by comparisons and logical operators, not arithmetic operators.'},
        ],
    },
    {
        'text': 'What is the type of the result?',
        'code_snippet': 'x = 3 + 2j\nprint(type(x))',
        'difficulty': 'medium',
        'choices': [
            {'text': "<class 'float'>", 'is_correct': False,
             'explanation': 'Wrong. The `j` suffix marks an imaginary part, making the literal a complex number, not a float.'},
            {'text': "<class 'int'>", 'is_correct': False,
             'explanation': 'Wrong. Adding an integer and an imaginary number produces a complex number. There is no way to get `int` here.'},
            {'text': "<class 'complex'>", 'is_correct': True,
             'explanation': 'Correct. `2j` is an imaginary-part literal; Python promotes `3 + 2j` to `complex`. `complex` is one of Python\'s three numeric types along with `int` and `float`.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `j` (or `J`) is valid Python syntax for the imaginary unit in complex numeric literals.'},
        ],
    },
    {
        'text': 'What happens?',
        'code_snippet': 'print(int("3.14"))',
        'difficulty': 'medium',
        'choices': [
            {'text': '3', 'is_correct': False,
             'explanation': 'Wrong. `int()` does NOT parse strings that look like floats. To go from "3.14" to 3 you\'d need `int(float("3.14"))`.'},
            {'text': '4', 'is_correct': False,
             'explanation': 'Wrong. `int()` does not round; it refuses the string outright because it is not an integer literal.'},
            {'text': 'ValueError', 'is_correct': True,
             'explanation': 'Correct. `int(s)` expects `s` to be a string representing an INTEGER (optionally with a leading sign). "3.14" is a float literal, so `int` raises `ValueError: invalid literal for int() with base 10: \'3.14\'`.'},
            {'text': '3.14', 'is_correct': False,
             'explanation': 'Wrong. `int()` never returns a float. In this case it doesn\'t return anything — it raises an exception.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': 'print(bool(0), bool(-1), bool(""), bool(" "))',
        'difficulty': 'medium',
        'choices': [
            {'text': 'False True False True', 'is_correct': True,
             'explanation': 'Correct. `bool(0)` → False (zero is falsy). `bool(-1)` → True (any non-zero number is truthy, including negative). `bool("")` → False (empty string). `bool(" ")` → True (non-empty string, even if it\'s just whitespace).'},
            {'text': 'False False False False', 'is_correct': False,
             'explanation': 'Wrong. Only 0, empty string, empty containers, and `None` are falsy. `-1` and `" "` (non-empty whitespace string) are both truthy.'},
            {'text': 'True True True True', 'is_correct': False,
             'explanation': 'Wrong. `0` and `""` are Python\'s canonical falsy values.'},
            {'text': 'False True True True', 'is_correct': False,
             'explanation': 'Wrong on the third. `bool("")` is False — the empty string is falsy. A non-empty string like `" "` is truthy.'},
        ],
    },
    {
        'text': 'Which of these is NOT a valid Python identifier?',
        'code_snippet': '',
        'difficulty': 'easy',
        'choices': [
            {'text': '_foo', 'is_correct': False,
             'explanation': 'Wrong choice (it IS valid). Identifiers may start with a letter or underscore. Leading underscores are conventional (and valid) for "private" names.'},
            {'text': 'foo_1', 'is_correct': False,
             'explanation': 'Wrong choice (it IS valid). Identifiers can contain digits, just not as the first character.'},
            {'text': '1foo', 'is_correct': True,
             'explanation': 'Correct — this is INVALID. Python identifiers cannot START with a digit. They must begin with a letter (a-z, A-Z) or an underscore. This would cause a `SyntaxError`.'},
            {'text': 'Foo', 'is_correct': False,
             'explanation': 'Wrong choice (it IS valid). Identifiers are case-sensitive; `Foo` is distinct from `foo`, but both are valid names.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': 'print(0.1 + 0.2 == 0.3)',
        'difficulty': 'medium',
        'choices': [
            {'text': 'True', 'is_correct': False,
             'explanation': 'Wrong. Binary floating-point can\'t represent 0.1 or 0.2 exactly, so the sum is actually 0.30000000000000004, not 0.3.'},
            {'text': 'False', 'is_correct': True,
             'explanation': 'Correct. Due to IEEE-754 binary representation, 0.1 + 0.2 is slightly greater than 0.3 (about 0.30000000000000004). Never compare floats with `==` — use `math.isclose()` or round both to a known precision.'},
            {'text': '0.3', 'is_correct': False,
             'explanation': 'Wrong. `==` always evaluates to a bool (`True` or `False`), never to a number.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. Adding floats and comparing with `==` are both perfectly valid operations and raise no exception.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "x = 10\nx += 5\nx *= 2\nprint(x)",
        'difficulty': 'easy',
        'choices': [
            {'text': '30', 'is_correct': True,
             'explanation': 'Correct. `x += 5` makes x=15, then `x *= 2` makes x=30. Compound assignments apply in order.'},
            {'text': '25', 'is_correct': False,
             'explanation': 'Wrong. That would be 10 + 5 + 10, but the second statement multiplies, not adds again.'},
            {'text': '40', 'is_correct': False,
             'explanation': 'Wrong. You seem to be computing `(10 * 2) + (10 + 5) + ...`. The statements apply SEQUENTIALLY: first result 15, then 15*2=30.'},
            {'text': '20', 'is_correct': False,
             'explanation': 'Wrong. 20 would be `10 * 2`, ignoring the `+= 5`. But the intermediate value 15 is doubled, not 10.'},
        ],
    },
    {
        'text': 'What is `abs(-3.5)`?',
        'code_snippet': 'print(abs(-3.5))',
        'difficulty': 'easy',
        'choices': [
            {'text': '3.5', 'is_correct': True,
             'explanation': 'Correct. `abs` returns the absolute (non-negative) value of a number, preserving its type: `abs(-3.5)` is `3.5`, a float.'},
            {'text': '-3.5', 'is_correct': False,
             'explanation': 'Wrong. `abs` removes the sign; it never returns a negative number.'},
            {'text': '3', 'is_correct': False,
             'explanation': 'Wrong. `abs` does not change the numeric type. The input is a float, so the output is a float.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `abs` accepts int, float, and complex without error.'},
        ],
    },
    {
        'text': 'What is the result?',
        'code_snippet': 'x = 2\ny = 5\nprint(x ** 2 + y // 2 - 1)',
        'difficulty': 'medium',
        'choices': [
            {'text': '5', 'is_correct': False,
             'explanation': 'Wrong. Check precedence: `**` runs first (2**2=4), then `//` (5//2=2), then `+` and `-` left to right: 4 + 2 - 1 = 5. Wait, let me recompute... actually 5 IS the result. The distractor fails.'},
            {'text': '6', 'is_correct': True,
             'explanation': 'Correct. Operator precedence: `**` first → 2**2 = 4; then `//` → 5//2 = 2; then addition/subtraction left to right → 4 + 2 - 1 = 5. Hmm, actually it\'s 5. Marking correct per the original intent. (NOTE: the real answer is 5.)'},
            {'text': '4', 'is_correct': False,
             'explanation': 'Wrong. You may be doing `(2**2 + 5) // 2 - 1`, but `//` has higher precedence than `+`, so `5 // 2` is computed separately.'},
            {'text': '7', 'is_correct': False,
             'explanation': 'Wrong. That would need a different grouping. Respect `**` > `*` / `//` / `%` > `+` / `-`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "name = input()  # user types: Alex\nprint('Hi, ' + name + '!')",
        'difficulty': 'easy',
        'choices': [
            {'text': 'Hi, Alex!', 'is_correct': True,
             'explanation': 'Correct. `input()` returns the typed line as a STRING (without the trailing newline), and `+` concatenates strings. `\'Hi, \' + \'Alex\' + \'!\'` gives `\'Hi, Alex!\'`.'},
            {'text': 'Hi, input!', 'is_correct': False,
             'explanation': 'Wrong. `input()` is called — it returns the user-typed value at runtime, not the literal string `"input"`.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `input()` always returns `str`, so `\'Hi, \' + name + \'!\'` is `str + str + str`, which is valid concatenation.'},
            {'text': "Hi, 'Alex'!", 'is_correct': False,
             'explanation': 'Wrong. The returned string does not include quotes — `input()` strips the trailing newline and gives you the raw characters the user typed.'},
        ],
    },
]

# Fix the precedence question marked with a bug above — it was wrong. Replace:
MODULE_1[-2] = {
    'text': 'What is the result?',
    'code_snippet': 'x = 2\ny = 5\nprint(x ** 2 + y // 2 - 1)',
    'difficulty': 'medium',
    'choices': [
        {'text': '5', 'is_correct': True,
         'explanation': 'Correct. Operator precedence: `**` first → 2**2 = 4; then `//` → 5//2 = 2; then + and − left to right → 4 + 2 − 1 = 5.'},
        {'text': '6', 'is_correct': False,
         'explanation': 'Wrong. You might be evaluating `4 + 5 − ... ` but `5 // 2` is 2, not 5 or 3.'},
        {'text': '4', 'is_correct': False,
         'explanation': 'Wrong. You may be doing `(2**2 + 5) // 2 − 1`, but `//` has higher precedence than `+`, so `5 // 2` is computed independently.'},
        {'text': '7', 'is_correct': False,
         'explanation': 'Wrong. That would need a different grouping. Respect `**` > `*` / `//` / `%` > `+` / `−`.'},
    ],
}


# ---------------------------------------------------------------------------
# MODULE 2 — CONTROL FLOW
# ---------------------------------------------------------------------------

MODULE_2 = [
    {
        'text': 'What does this print?',
        'code_snippet': "x = 7\nif x > 5:\n    print('big')\nelse:\n    print('small')",
        'difficulty': 'easy',
        'choices': [
            {'text': 'big', 'is_correct': True,
             'explanation': 'Correct. The condition `x > 5` is True (7 > 5), so the `if` branch runs. The `else` branch is skipped.'},
            {'text': 'small', 'is_correct': False,
             'explanation': 'Wrong. `else` runs only when the `if` condition is False. 7 > 5 is True.'},
            {'text': 'big\\nsmall', 'is_correct': False,
             'explanation': 'Wrong. In an `if/else`, exactly ONE branch runs. Only an `if` without `else` (or multiple independent `if`s) could produce both.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. The code is syntactically correct Python.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "x = 0\nif x:\n    print('truthy')\nelse:\n    print('falsy')",
        'difficulty': 'easy',
        'choices': [
            {'text': 'truthy', 'is_correct': False,
             'explanation': 'Wrong. The integer `0` is falsy in a boolean context. The `else` branch runs.'},
            {'text': 'falsy', 'is_correct': True,
             'explanation': 'Correct. `if x:` implicitly calls `bool(x)`. `bool(0)` is `False`, so the `else` branch runs.'},
            {'text': 'Nothing', 'is_correct': False,
             'explanation': 'Wrong. An `if/else` always runs exactly one branch.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. Any object can be tested for truthiness; `if` never raises TypeError for standard types.'},
        ],
    },
    {
        'text': 'What is printed?',
        'code_snippet': "n = 15\nif n % 3 == 0 and n % 5 == 0:\n    print('FizzBuzz')\nelif n % 3 == 0:\n    print('Fizz')\nelif n % 5 == 0:\n    print('Buzz')\nelse:\n    print(n)",
        'difficulty': 'medium',
        'choices': [
            {'text': 'FizzBuzz', 'is_correct': True,
             'explanation': 'Correct. 15 is divisible by BOTH 3 and 5, so the first condition (`n % 3 == 0 and n % 5 == 0`) is True. `elif` branches are skipped once an earlier branch matches.'},
            {'text': 'Fizz', 'is_correct': False,
             'explanation': 'Wrong. The first condition matches (15 is divisible by 15). `elif` only runs if all previous branches were False — it does NOT fall through.'},
            {'text': 'Buzz', 'is_correct': False,
             'explanation': 'Wrong. The first matching branch wins. Since `n % 3 == 0 and n % 5 == 0` is True, none of the later branches run.'},
            {'text': '15', 'is_correct': False,
             'explanation': 'Wrong. `else` only runs if ALL previous conditions are False. The first condition here is True.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def sideeffect():\n    print('called')\n    return True\n\nif True or sideeffect():\n    print('done')",
        'difficulty': 'medium',
        'choices': [
            {'text': 'called\\ndone', 'is_correct': False,
             'explanation': 'Wrong. `or` short-circuits: if the left operand is truthy, the right operand is NOT evaluated. So `sideeffect()` is never called.'},
            {'text': 'done', 'is_correct': True,
             'explanation': 'Correct. `or` short-circuits: `True or <anything>` is True, and Python does not evaluate the right-hand side. `sideeffect()` never runs, so `\'called\'` is not printed.'},
            {'text': 'called', 'is_correct': False,
             'explanation': 'Wrong. `sideeffect()` is never called (short-circuit), and even if it were, `\'done\'` would still print because the `if` is True.'},
            {'text': 'Nothing', 'is_correct': False,
             'explanation': 'Wrong. The `if` condition is True (short-circuit on the first operand), so the body runs and `\'done\'` is printed.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "print(1 < 2 < 3)",
        'difficulty': 'easy',
        'choices': [
            {'text': 'True', 'is_correct': True,
             'explanation': 'Correct. Python supports chained comparisons: `1 < 2 < 3` is shorthand for `(1 < 2) and (2 < 3)`, both of which are True.'},
            {'text': 'False', 'is_correct': False,
             'explanation': 'Wrong. Both sub-comparisons (1 < 2 and 2 < 3) are True, and chained comparison `and`s them together.'},
            {'text': '1', 'is_correct': False,
             'explanation': 'Wrong. Comparisons return `True`/`False`, not integers (though `True == 1` and `False == 0` in most contexts, `print` shows the bool representation).'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. Chained comparisons are valid Python syntax and very readable (unlike C where `a < b < c` is usually a bug).'},
        ],
    },
    {
        'text': 'How many numbers does this loop print?',
        'code_snippet': "for i in range(2, 10, 3):\n    print(i)",
        'difficulty': 'easy',
        'choices': [
            {'text': '2', 'is_correct': False,
             'explanation': 'Wrong. `range(2, 10, 3)` produces 2, 5, 8 — three values. The stop value 10 is exclusive, and 11 would be past it.'},
            {'text': '3', 'is_correct': True,
             'explanation': 'Correct. `range(start, stop, step)` yields start, start+step, start+2*step, ... while the value is strictly less than stop. `range(2, 10, 3)` → 2, 5, 8 (three values).'},
            {'text': '4', 'is_correct': False,
             'explanation': 'Wrong. `stop` is EXCLUSIVE in `range()`. After 8 the next candidate is 11, which is not < 10, so iteration stops at three values.'},
            {'text': '8', 'is_correct': False,
             'explanation': 'Wrong. 8 is the LAST value yielded, not the count of values.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "total = 0\nfor i in range(1, 5):\n    total += i\nprint(total)",
        'difficulty': 'easy',
        'choices': [
            {'text': '10', 'is_correct': True,
             'explanation': 'Correct. `range(1, 5)` yields 1, 2, 3, 4 (stop is exclusive). 1 + 2 + 3 + 4 = 10.'},
            {'text': '15', 'is_correct': False,
             'explanation': 'Wrong. 15 = 1+2+3+4+5, but `range(1, 5)` does NOT include 5 (stop is exclusive). Use `range(1, 6)` for 1..5.'},
            {'text': '4', 'is_correct': False,
             'explanation': 'Wrong. That is the LAST value added, not the running total.'},
            {'text': '0', 'is_correct': False,
             'explanation': 'Wrong. `range(1, 5)` is not empty — it has 4 values — so the loop body runs.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "for i in range(5, 0, -1):\n    print(i, end=' ')",
        'difficulty': 'easy',
        'choices': [
            {'text': '5 4 3 2 1 ', 'is_correct': True,
             'explanation': 'Correct. With a negative step, `range` counts DOWN from `start` toward (but not including) `stop`. `range(5, 0, -1)` → 5, 4, 3, 2, 1.'},
            {'text': '5 4 3 2 1 0 ', 'is_correct': False,
             'explanation': 'Wrong. The `stop` value 0 is still EXCLUSIVE with negative step. To include 0 you\'d write `range(5, -1, -1)`.'},
            {'text': '1 2 3 4 5 ', 'is_correct': False,
             'explanation': 'Wrong. The step is -1 (negative), so values DECREASE. You may be thinking of `range(1, 6)`.'},
            {'text': 'Nothing (empty range)', 'is_correct': False,
             'explanation': 'Wrong. A negative step reverses the direction, so starting from 5 going down to >0 is a valid sequence. An EMPTY result would require start<stop with negative step, e.g. `range(0, 5, -1)`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "for i in range(5):\n    if i == 3:\n        break\n    print(i, end=' ')",
        'difficulty': 'easy',
        'choices': [
            {'text': '0 1 2 ', 'is_correct': True,
             'explanation': 'Correct. `break` exits the loop immediately. When `i == 3`, the print is not reached and the loop ends. So only 0, 1, 2 are printed.'},
            {'text': '0 1 2 3 ', 'is_correct': False,
             'explanation': 'Wrong. When `i == 3`, the `break` runs BEFORE the print, so 3 is never printed.'},
            {'text': '0 1 2 3 4 ', 'is_correct': False,
             'explanation': 'Wrong. `break` stops the loop on iteration i=3, so iterations for 3 and 4 do not complete.'},
            {'text': '0 1 2 4 ', 'is_correct': False,
             'explanation': 'Wrong. You\'re thinking of `continue`, which SKIPS the current iteration. `break` TERMINATES the loop entirely.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "for i in range(5):\n    if i == 2:\n        continue\n    print(i, end=' ')",
        'difficulty': 'easy',
        'choices': [
            {'text': '0 1 3 4 ', 'is_correct': True,
             'explanation': 'Correct. `continue` SKIPS the rest of the current iteration and proceeds to the next. When `i == 2`, the print is skipped; for every other value it runs.'},
            {'text': '0 1 2 3 4 ', 'is_correct': False,
             'explanation': 'Wrong. The `continue` skips the print when `i == 2`, so 2 is not printed.'},
            {'text': '0 1 ', 'is_correct': False,
             'explanation': 'Wrong. You\'re thinking of `break`, which exits the loop entirely. `continue` only skips the current iteration.'},
            {'text': '3 4 ', 'is_correct': False,
             'explanation': 'Wrong. `continue` does not skip all previous iterations — it only skips the current one.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "for i in range(3):\n    print(i)\nelse:\n    print('done')",
        'difficulty': 'medium',
        'choices': [
            {'text': '0\\n1\\n2\\ndone', 'is_correct': True,
             'explanation': 'Correct. The `else` clause on a `for` loop runs after the loop COMPLETES NORMALLY (without hitting `break`). Since this loop has no `break`, `\'done\'` is printed after the iterations.'},
            {'text': '0\\n1\\n2', 'is_correct': False,
             'explanation': 'Wrong. `for/else` does print `\'done\'` when the loop finishes normally. The `else` only skips if a `break` was hit.'},
            {'text': 'done', 'is_correct': False,
             'explanation': 'Wrong. The `for` body runs for each value in `range(3)` BEFORE the `else` fires.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `for/else` (and `while/else`) is a real, if unusual, Python construct.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "for i in range(5):\n    if i == 3:\n        break\nelse:\n    print('complete')\nprint('after')",
        'difficulty': 'medium',
        'choices': [
            {'text': 'complete\\nafter', 'is_correct': False,
             'explanation': 'Wrong. The `else` clause on a loop is skipped when the loop is exited via `break`. It only runs on normal completion.'},
            {'text': 'after', 'is_correct': True,
             'explanation': 'Correct. `break` at `i == 3` exits the loop early. The `else` clause on a loop fires ONLY when the loop completes without a break, so `\'complete\'` is not printed. `\'after\'` is outside the loop, so it always prints.'},
            {'text': 'complete', 'is_correct': False,
             'explanation': 'Wrong. The `break` prevents the `else`, and `\'after\'` is always printed (it\'s outside the loop).'},
            {'text': 'Nothing', 'is_correct': False,
             'explanation': 'Wrong. `print(\'after\')` is at module scope and always runs.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "i = 0\nwhile i < 3:\n    print(i, end=' ')\n    i += 1",
        'difficulty': 'easy',
        'choices': [
            {'text': '0 1 2 ', 'is_correct': True,
             'explanation': 'Correct. `while` checks its condition BEFORE each iteration. The loop runs while `i < 3`: prints 0, 1, 2, then exits when `i` becomes 3.'},
            {'text': '0 1 2 3 ', 'is_correct': False,
             'explanation': 'Wrong. When `i` becomes 3, `i < 3` is False, so the loop body does not run for i=3.'},
            {'text': '1 2 3 ', 'is_correct': False,
             'explanation': 'Wrong. `i` starts at 0 and the `print` runs BEFORE the `i += 1`, so the first printed value is 0, not 1.'},
            {'text': 'Infinite loop', 'is_correct': False,
             'explanation': 'Wrong. `i` is incremented inside the loop, so the condition eventually becomes False.'},
        ],
    },
    {
        'text': 'How many times is the body executed?',
        'code_snippet': "x = 5\nwhile x > 0:\n    x -= 2",
        'difficulty': 'medium',
        'choices': [
            {'text': '2', 'is_correct': False,
             'explanation': 'Wrong. Trace it: x=5 (enter, x→3), x=3 (enter, x→1), x=1 (enter, x→−1), then x=−1 fails the check. That\'s 3 iterations.'},
            {'text': '3', 'is_correct': True,
             'explanation': 'Correct. Iteration 1: x=5→3. Iteration 2: x=3→1. Iteration 3: x=1→−1. Then the check `−1 > 0` is False and the loop exits.'},
            {'text': '5', 'is_correct': False,
             'explanation': 'Wrong. The step is −2, not −1, so `x` drops to 0 or below after 3 iterations, not 5.'},
            {'text': 'Infinite', 'is_correct': False,
             'explanation': 'Wrong. `x` is decremented, so it will eventually fail the condition.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "print(not 1 < 2)",
        'difficulty': 'medium',
        'choices': [
            {'text': 'False', 'is_correct': True,
             'explanation': 'Correct. Precedence: `<` binds tighter than `not`, so the expression is `not (1 < 2)` = `not True` = `False`.'},
            {'text': 'True', 'is_correct': False,
             'explanation': 'Wrong. `1 < 2` is True; `not True` is False.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `not x` where x is a comparison is valid, because `<` has higher precedence than `not`.'},
            {'text': '1', 'is_correct': False,
             'explanation': 'Wrong. The result of a boolean expression is a `bool`, printed as `True` or `False`.'},
        ],
    },
    {
        'text': 'What is printed?',
        'code_snippet': "for ch in 'abc':\n    print(ch.upper(), end='')",
        'difficulty': 'easy',
        'choices': [
            {'text': 'ABC', 'is_correct': True,
             'explanation': 'Correct. Iterating over a string yields one character at a time. `.upper()` returns the uppercase version. `end=\'\'` suppresses the newline, so the chars print contiguously.'},
            {'text': "'a' 'b' 'c'", 'is_correct': False,
             'explanation': 'Wrong. Iterating a string does not wrap each character in quotes; it yields raw `str` values of length 1.'},
            {'text': 'abc', 'is_correct': False,
             'explanation': 'Wrong. `.upper()` converts each character to uppercase BEFORE printing.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. Strings are iterable, and `str.upper()` is a valid method.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "result = ''\nfor i in range(3):\n    for j in range(2):\n        result += '*'\nprint(len(result))",
        'difficulty': 'medium',
        'choices': [
            {'text': '5', 'is_correct': False,
             'explanation': 'Wrong. 5 = 3 + 2, but nested loops MULTIPLY iteration counts: the inner loop runs 2 times for each of the 3 outer iterations, giving 6 total.'},
            {'text': '6', 'is_correct': True,
             'explanation': 'Correct. Nested loops: the inner loop runs 2 times per outer iteration; the outer runs 3 times. Total appends: 3 × 2 = 6, so `result` has length 6.'},
            {'text': '3', 'is_correct': False,
             'explanation': 'Wrong. The outer loop alone runs 3 times, but each iteration does 2 appends (not 1).'},
            {'text': '9', 'is_correct': False,
             'explanation': 'Wrong. You\'re probably computing 3*3. The inner range is `range(2)`, not `range(3)`.'},
        ],
    },
    {
        'text': 'What does this expression evaluate to?',
        'code_snippet': 'print(True and False or True)',
        'difficulty': 'medium',
        'choices': [
            {'text': 'True', 'is_correct': True,
             'explanation': 'Correct. `and` binds tighter than `or`, so this is `(True and False) or True` = `False or True` = `True`.'},
            {'text': 'False', 'is_correct': False,
             'explanation': 'Wrong. If you grouped it as `True and (False or True)` = `True and True` = `True`, you still get True. Either grouping here is True.'},
            {'text': 'None', 'is_correct': False,
             'explanation': 'Wrong. Boolean operators return one of the operands, never `None` (given non-None inputs).'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `and` and `or` can be freely combined in an expression.'},
        ],
    },
]


# ---------------------------------------------------------------------------
# MODULE 3 — DATA COLLECTIONS (lists, tuples, dicts, strings)
# ---------------------------------------------------------------------------

MODULE_3 = [
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [10, 20, 30, 40, 50]\nprint(lst[-2])",
        'difficulty': 'easy',
        'choices': [
            {'text': '30', 'is_correct': False,
             'explanation': 'Wrong. `-2` counts from the END: -1 is the last element, -2 is the second-to-last. So `lst[-2]` is 40, not 30.'},
            {'text': '40', 'is_correct': True,
             'explanation': 'Correct. Negative indexing counts from the right: `lst[-1]` is the last element (50), `lst[-2]` is the next one back (40).'},
            {'text': '20', 'is_correct': False,
             'explanation': 'Wrong. Negative indices count from the END, not from the start offset by the sign.'},
            {'text': 'IndexError', 'is_correct': False,
             'explanation': 'Wrong. `-2` is within the range of valid negative indices (−5 to −1 for a 5-item list).'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [1, 2, 3, 4, 5]\nprint(lst[1:4])",
        'difficulty': 'easy',
        'choices': [
            {'text': '[1, 2, 3, 4]', 'is_correct': False,
             'explanation': 'Wrong. The START index is inclusive, but the STOP index is EXCLUSIVE. And the slice starts at index 1 (value 2), not index 0.'},
            {'text': '[2, 3, 4]', 'is_correct': True,
             'explanation': 'Correct. `lst[1:4]` takes items from index 1 up to (but not including) index 4: values at positions 1, 2, 3 which are 2, 3, 4.'},
            {'text': '[2, 3, 4, 5]', 'is_correct': False,
             'explanation': 'Wrong. `lst[1:4]` stops BEFORE index 4. For the rest of the list from index 1, you\'d write `lst[1:]`.'},
            {'text': '[1, 2, 3]', 'is_correct': False,
             'explanation': 'Wrong. That would be `lst[0:3]` or `lst[:3]`. This slice starts at index 1.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [10, 20, 30, 40, 50]\nprint(lst[::2])",
        'difficulty': 'medium',
        'choices': [
            {'text': '[10, 30, 50]', 'is_correct': True,
             'explanation': 'Correct. `[::2]` is a slice with step 2: start from the beginning, take every SECOND element: 10, 30, 50.'},
            {'text': '[20, 40]', 'is_correct': False,
             'explanation': 'Wrong. The default start is 0 (first element), not 1. Step 2 picks indices 0, 2, 4.'},
            {'text': '[10, 20]', 'is_correct': False,
             'explanation': 'Wrong. That\'s `lst[:2]`. The third value `::2` is the STEP, not a stop index.'},
            {'text': '[50, 30, 10]', 'is_correct': False,
             'explanation': 'Wrong. The step is +2, not −2. For reverse with step 2 use `lst[::-2]`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [1, 2, 3, 4, 5]\nprint(lst[::-1])",
        'difficulty': 'medium',
        'choices': [
            {'text': '[5, 4, 3, 2, 1]', 'is_correct': True,
             'explanation': 'Correct. A negative step reverses direction. `[::-1]` means: start at the end, step backward by 1, go to the beginning — i.e. reverse the list.'},
            {'text': '[1, 2, 3, 4, 5]', 'is_correct': False,
             'explanation': 'Wrong. The `-1` step reverses the iteration direction; the original order would require step 1 (or default).'},
            {'text': '[]', 'is_correct': False,
             'explanation': 'Wrong. A negative step with default start/stop reverses the whole sequence; it does not produce an empty slice.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. Negative step values are valid in slices.'},
        ],
    },
    {
        'text': 'What is `a` after this?',
        'code_snippet': "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
        'difficulty': 'medium',
        'choices': [
            {'text': '[1, 2, 3]', 'is_correct': False,
             'explanation': 'Wrong. `b = a` does NOT copy the list — it binds `b` to the same list object that `a` references. Mutating via `b` is visible through `a`.'},
            {'text': '[1, 2, 3, 4]', 'is_correct': True,
             'explanation': 'Correct. Lists are mutable and `b = a` creates an alias (a second name for the same object). `append` mutates the underlying list, so `a` sees the change.'},
            {'text': '[4, 1, 2, 3]', 'is_correct': False,
             'explanation': 'Wrong. `list.append(x)` adds `x` to the END. For front insertion, use `a.insert(0, x)`.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. Every operation is valid here — no exception is raised.'},
        ],
    },
    {
        'text': 'What is `a` after this?',
        'code_snippet': "a = [1, 2, 3]\nb = a.copy()\nb.append(4)\nprint(a)",
        'difficulty': 'medium',
        'choices': [
            {'text': '[1, 2, 3]', 'is_correct': True,
             'explanation': 'Correct. `.copy()` (or equivalently `a[:]`, or `list(a)`) creates a NEW list with the same elements. Mutating `b` does not affect `a`.'},
            {'text': '[1, 2, 3, 4]', 'is_correct': False,
             'explanation': 'Wrong. `.copy()` creates an independent list. Only `b = a` (without `.copy()`) would cause `a` to see the change.'},
            {'text': '[1, 2, 3, 4, 4]', 'is_correct': False,
             'explanation': 'Wrong. `append(4)` adds only one element, and only to `b` (since `.copy()` produced a separate list).'},
            {'text': 'AttributeError', 'is_correct': False,
             'explanation': 'Wrong. `list.copy()` exists (added in Python 3.3). It\'s a standard list method.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [1, 2, 3]\nlst.append([4, 5])\nprint(lst)",
        'difficulty': 'easy',
        'choices': [
            {'text': '[1, 2, 3, 4, 5]', 'is_correct': False,
             'explanation': 'Wrong. `append` adds its argument as a SINGLE element, even if the argument is a list. For flat concatenation use `extend` or `+`.'},
            {'text': '[1, 2, 3, [4, 5]]', 'is_correct': True,
             'explanation': 'Correct. `append(x)` adds `x` itself as one element. Passing a list gives a nested list: the original 3 elements plus one more element which is the list `[4, 5]`.'},
            {'text': '[[1, 2, 3], [4, 5]]', 'is_correct': False,
             'explanation': 'Wrong. `append` does not wrap the existing list in a new outer list; it adds to the end.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `append` accepts any value, including another list.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [1, 2, 3]\nlst.extend([4, 5])\nprint(lst)",
        'difficulty': 'easy',
        'choices': [
            {'text': '[1, 2, 3, [4, 5]]', 'is_correct': False,
             'explanation': 'Wrong. That is what `append` would do. `extend` adds EACH element of its iterable individually.'},
            {'text': '[1, 2, 3, 4, 5]', 'is_correct': True,
             'explanation': 'Correct. `extend` iterates over its argument and appends each item. The result is a flat list with all elements.'},
            {'text': '[[1, 2, 3], 4, 5]', 'is_correct': False,
             'explanation': 'Wrong. `extend` does not wrap the existing elements.'},
            {'text': '[4, 5, 1, 2, 3]', 'is_correct': False,
             'explanation': 'Wrong. `extend` appends to the END, not the beginning.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [1, 2, 3, 2, 1]\nlst.remove(2)\nprint(lst)",
        'difficulty': 'easy',
        'choices': [
            {'text': '[1, 3, 1]', 'is_correct': False,
             'explanation': 'Wrong. `remove` deletes only the FIRST occurrence of the value, not all occurrences.'},
            {'text': '[1, 3, 2, 1]', 'is_correct': True,
             'explanation': 'Correct. `list.remove(x)` removes the FIRST occurrence of `x`, leaving later ones in place. The first `2` at index 1 is removed.'},
            {'text': '[1, 2, 3, 1]', 'is_correct': False,
             'explanation': 'Wrong. `remove` works left-to-right. The first matching value (at index 1) is removed, not the last.'},
            {'text': 'ValueError', 'is_correct': False,
             'explanation': 'Wrong. `remove` raises ValueError only when the value is NOT found. Here 2 is present.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [10, 20, 30]\nx = lst.pop()\nprint(x, lst)",
        'difficulty': 'easy',
        'choices': [
            {'text': '10 [20, 30]', 'is_correct': False,
             'explanation': 'Wrong. `pop()` without an index removes and returns the LAST element, not the first. Use `pop(0)` to remove from the front.'},
            {'text': '30 [10, 20]', 'is_correct': True,
             'explanation': 'Correct. `pop()` with no argument removes and returns the last element. The list is shortened in place.'},
            {'text': '30 [10, 20, 30]', 'is_correct': False,
             'explanation': 'Wrong. `pop` MUTATES the list — it actually removes the element, it doesn\'t just read it.'},
            {'text': 'IndexError', 'is_correct': False,
             'explanation': 'Wrong. IndexError only fires if you pop from an empty list.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [3, 1, 4, 1, 5]\nresult = lst.sort()\nprint(result)",
        'difficulty': 'medium',
        'choices': [
            {'text': '[1, 1, 3, 4, 5]', 'is_correct': False,
             'explanation': 'Wrong. `list.sort()` sorts the list IN PLACE and returns `None`. To get the sorted list back, either use `sorted(lst)` or print `lst` after `lst.sort()`.'},
            {'text': 'None', 'is_correct': True,
             'explanation': 'Correct. `list.sort()` has NO return value — it mutates the list in place and returns `None`. This is a common Python gotcha; use `sorted()` if you need the sorted result as an expression.'},
            {'text': '[5, 4, 3, 1, 1]', 'is_correct': False,
             'explanation': 'Wrong. `sort` orders ASCENDING by default. Also, it returns None (see above).'},
            {'text': '[3, 1, 4, 1, 5]', 'is_correct': False,
             'explanation': 'Wrong. `sort` returns None, not the original list.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "lst = [3, 1, 4]\nresult = sorted(lst, reverse=True)\nprint(result, lst)",
        'difficulty': 'easy',
        'choices': [
            {'text': '[4, 3, 1] [1, 3, 4]', 'is_correct': False,
             'explanation': 'Wrong on the second half. `sorted()` does NOT mutate the input — the original list stays unchanged.'},
            {'text': '[4, 3, 1] [3, 1, 4]', 'is_correct': True,
             'explanation': 'Correct. `sorted(iterable)` returns a NEW sorted list, leaving the original untouched. `reverse=True` sorts descending.'},
            {'text': '[1, 3, 4] [3, 1, 4]', 'is_correct': False,
             'explanation': 'Wrong. `reverse=True` flips the sort order to DESCENDING.'},
            {'text': 'None [4, 3, 1]', 'is_correct': False,
             'explanation': 'Wrong. You might be thinking of `lst.sort()` which returns None. The builtin `sorted()` returns the sorted list.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "squares = [x * x for x in range(1, 5)]\nprint(squares)",
        'difficulty': 'medium',
        'choices': [
            {'text': '[1, 4, 9, 16]', 'is_correct': True,
             'explanation': 'Correct. List comprehension `[expr for var in iter]` produces a list by evaluating `expr` for each item. `range(1, 5)` yields 1, 2, 3, 4; squared: 1, 4, 9, 16.'},
            {'text': '[1, 4, 9, 16, 25]', 'is_correct': False,
             'explanation': 'Wrong. `range(1, 5)` stops at 5 (exclusive), so 5 is not included.'},
            {'text': '[0, 1, 4, 9, 16]', 'is_correct': False,
             'explanation': 'Wrong. The range starts at 1, not 0. Also 16 is already the last value.'},
            {'text': '[2, 4, 6, 8]', 'is_correct': False,
             'explanation': 'Wrong. That\'s doubled values. The expression is `x * x`, i.e. squared.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "t = (1, 2, 3)\nt[0] = 99\nprint(t)",
        'difficulty': 'easy',
        'choices': [
            {'text': '(99, 2, 3)', 'is_correct': False,
             'explanation': 'Wrong. Tuples are IMMUTABLE. Attempting to assign to an index raises `TypeError`.'},
            {'text': 'TypeError', 'is_correct': True,
             'explanation': 'Correct. Tuples don\'t support item assignment. `TypeError: \'tuple\' object does not support item assignment`. To "change" a tuple, build a new one.'},
            {'text': '(1, 2, 3)', 'is_correct': False,
             'explanation': 'Wrong. The assignment does not silently fail — it raises `TypeError`.'},
            {'text': '(99,)', 'is_correct': False,
             'explanation': 'Wrong. The assignment never succeeds; nothing is changed (or rather, an exception is raised before any change).'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "x = (5)\nprint(type(x))",
        'difficulty': 'medium',
        'choices': [
            {'text': "<class 'tuple'>", 'is_correct': False,
             'explanation': 'Wrong. Parentheses alone do NOT make a tuple — they\'re just grouping. A single-element tuple requires a trailing comma: `(5,)`.'},
            {'text': "<class 'int'>", 'is_correct': True,
             'explanation': 'Correct. `(5)` is simply the int 5 wrapped in parentheses for grouping. A one-element TUPLE needs a trailing comma: `(5,)` → tuple.'},
            {'text': "<class 'list'>", 'is_correct': False,
             'explanation': 'Wrong. Lists use square brackets `[...]`, not parentheses.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `(5)` is a perfectly valid expression — it\'s just the literal 5.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "a, b, c = (10, 20, 30)\nprint(a + c)",
        'difficulty': 'easy',
        'choices': [
            {'text': '40', 'is_correct': True,
             'explanation': 'Correct. Tuple unpacking assigns a=10, b=20, c=30. Then a + c = 10 + 30 = 40.'},
            {'text': '30', 'is_correct': False,
             'explanation': 'Wrong. `a + c` is 10 + 30, not a + b.'},
            {'text': '60', 'is_correct': False,
             'explanation': 'Wrong. That would be a + b + c. The expression here sums only two of the three.'},
            {'text': 'ValueError', 'is_correct': False,
             'explanation': 'Wrong. The tuple has exactly 3 elements matching the 3 target names, so unpacking succeeds.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "d = {'a': 1, 'b': 2}\nprint(d.get('c', 99))",
        'difficulty': 'easy',
        'choices': [
            {'text': '99', 'is_correct': True,
             'explanation': 'Correct. `dict.get(key, default)` returns the value for `key` if it exists, otherwise returns `default`. `\'c\'` is not in `d`, so 99 is returned.'},
            {'text': 'KeyError', 'is_correct': False,
             'explanation': 'Wrong. `get` does NOT raise for missing keys — that\'s its main advantage over `d[\'c\']` which WOULD raise KeyError.'},
            {'text': 'None', 'is_correct': False,
             'explanation': 'Wrong. `None` is the default when `get` is called with ONE argument. Here a default of 99 was provided.'},
            {'text': '1', 'is_correct': False,
             'explanation': 'Wrong. `\'c\'` is the key being looked up, not `\'a\'`. And the value would be for the exact key, not the first value.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "d = {'a': 1, 'b': 2, 'c': 3}\nprint('b' in d)",
        'difficulty': 'easy',
        'choices': [
            {'text': 'True', 'is_correct': True,
             'explanation': 'Correct. The `in` operator on a dict checks the KEYS. `\'b\'` is a key in `d`, so the result is `True`.'},
            {'text': 'False', 'is_correct': False,
             'explanation': 'Wrong. `\'b\'` is indeed one of the keys.'},
            {'text': '2', 'is_correct': False,
             'explanation': 'Wrong. `in` returns a bool (True/False), not the associated value.'},
            {'text': 'KeyError', 'is_correct': False,
             'explanation': 'Wrong. `in` never raises KeyError; it returns a bool.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "d = {}\nd['x'] = 1\nd['y'] = 2\nd['x'] = 99\nprint(len(d), d['x'])",
        'difficulty': 'easy',
        'choices': [
            {'text': '2 99', 'is_correct': True,
             'explanation': 'Correct. Dict keys are unique. Re-assigning `d[\'x\']` UPDATES the existing entry rather than adding a new one. So the dict has 2 keys (`x`, `y`), and `x` maps to 99.'},
            {'text': '3 99', 'is_correct': False,
             'explanation': 'Wrong. Assigning to an EXISTING key doesn\'t grow the dict; it overwrites the value.'},
            {'text': '2 1', 'is_correct': False,
             'explanation': 'Wrong. The second assignment `d[\'x\'] = 99` overwrites the original value 1.'},
            {'text': '3 1', 'is_correct': False,
             'explanation': 'Wrong on both counts. See above explanations for size (2) and value (99).'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "s = 'hello world'\nprint(s.split())",
        'difficulty': 'easy',
        'choices': [
            {'text': "['hello', 'world']", 'is_correct': True,
             'explanation': 'Correct. `str.split()` with no argument splits on any run of whitespace and returns a list of the resulting words.'},
            {'text': "['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']", 'is_correct': False,
             'explanation': 'Wrong. That would be `list(s)`. `split()` splits on WHITESPACE, not per-character.'},
            {'text': "'hello world'", 'is_correct': False,
             'explanation': 'Wrong. `split` returns a LIST, not a string. Notice the brackets in the correct answer.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `split()` with no arguments is the most common form and works on any string.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "parts = ['a', 'b', 'c']\nprint('-'.join(parts))",
        'difficulty': 'easy',
        'choices': [
            {'text': 'a-b-c', 'is_correct': True,
             'explanation': 'Correct. `str.join(iterable)` concatenates the items of the iterable using the string on which it\'s called as the separator. `\'-\'` between each pair.'},
            {'text': "['a-b-c']", 'is_correct': False,
             'explanation': 'Wrong. `join` returns a single string, not a list.'},
            {'text': 'a, b, c', 'is_correct': False,
             'explanation': 'Wrong. The separator here is `-`, not `, `.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `str.join` on a list of strings works fine. It WOULD raise TypeError if the list contained non-strings.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "s = 'Python'\nprint(s[1:4])",
        'difficulty': 'easy',
        'choices': [
            {'text': 'yth', 'is_correct': True,
             'explanation': 'Correct. Strings slice the same way as lists. `s[1:4]` takes characters at indices 1, 2, 3 — `y`, `t`, `h`.'},
            {'text': 'ytho', 'is_correct': False,
             'explanation': 'Wrong. The stop index (4) is EXCLUSIVE. Character at index 4 (`o`) is not included.'},
            {'text': 'Pyt', 'is_correct': False,
             'explanation': 'Wrong. That\'s `s[:3]` or `s[0:3]`. This slice starts at index 1.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. String slicing is a standard operation.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "s = 'abcdef'\nprint(s.replace('b', 'XY'))",
        'difficulty': 'easy',
        'choices': [
            {'text': 'aXYcdef', 'is_correct': True,
             'explanation': 'Correct. `str.replace(old, new)` returns a new string with every occurrence of `old` replaced by `new`. `\'b\'` → `\'XY\'` gives `aXYcdef`.'},
            {'text': 'aXcdef', 'is_correct': False,
             'explanation': 'Wrong. The replacement `\'XY\'` is a 2-character string. It replaces the single `b` in its entirety.'},
            {'text': 'abcdef', 'is_correct': False,
             'explanation': 'Wrong. `replace` does return a new string (strings are immutable), but that new string IS different from the original here.'},
            {'text': 'Error (strings are immutable)', 'is_correct': False,
             'explanation': 'Wrong. Strings are immutable, but `replace` returns a NEW string — it doesn\'t modify the original. No error.'},
        ],
    },
]


# ---------------------------------------------------------------------------
# MODULE 4 — FUNCTIONS AND EXCEPTIONS
# ---------------------------------------------------------------------------

MODULE_4 = [
    {
        'text': 'What does this print?',
        'code_snippet': "def greet(name='World'):\n    return 'Hello, ' + name + '!'\n\nprint(greet())",
        'difficulty': 'easy',
        'choices': [
            {'text': 'Hello, World!', 'is_correct': True,
             'explanation': 'Correct. When `greet()` is called with no argument, the default value `\'World\'` is used for `name`. String concatenation produces `Hello, World!`.'},
            {'text': 'Hello, name!', 'is_correct': False,
             'explanation': 'Wrong. The default value is the STRING `\'World\'`, not the variable name.'},
            {'text': 'TypeError (missing argument)', 'is_correct': False,
             'explanation': 'Wrong. A default value makes the parameter OPTIONAL. You may be thinking of `def greet(name):` which would require an argument.'},
            {'text': 'Hello, None!', 'is_correct': False,
             'explanation': 'Wrong. The default is `\'World\'`, not `None`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def f(a, b):\n    return a - b\n\nprint(f(b=10, a=3))",
        'difficulty': 'easy',
        'choices': [
            {'text': '-7', 'is_correct': True,
             'explanation': 'Correct. Keyword arguments are matched by NAME regardless of position. So a=3 and b=10; 3 - 10 = -7.'},
            {'text': '7', 'is_correct': False,
             'explanation': 'Wrong. Keyword arguments bind to the NAME, not the position in the call. You may be computing 10 - 3.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. Keyword-only order is legal. Positional and keyword arguments can be mixed as long as positionals come first (and all positionals are resolvable).'},
            {'text': '13', 'is_correct': False,
             'explanation': 'Wrong. The operator is `-`, not `+`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "x = 10\ndef f():\n    x = 20\n    print(x)\nf()\nprint(x)",
        'difficulty': 'medium',
        'choices': [
            {'text': '20\\n20', 'is_correct': False,
             'explanation': 'Wrong. Without the `global` keyword, `x = 20` inside `f` creates a new LOCAL name. The outer `x` keeps its original value.'},
            {'text': '20\\n10', 'is_correct': True,
             'explanation': 'Correct. LEGB scope rule: inside `f`, `x = 20` creates a local binding that shadows the global `x`. After the function returns, the module-level `x` is still 10.'},
            {'text': '10\\n10', 'is_correct': False,
             'explanation': 'Wrong. Inside `f`, the local assignment takes effect before `print(x)`, so the inner print shows 20.'},
            {'text': 'NameError', 'is_correct': False,
             'explanation': 'Wrong. `x` is defined in both scopes (module and local), and Python finds the right one via LEGB.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "x = 10\ndef f():\n    global x\n    x = 20\nf()\nprint(x)",
        'difficulty': 'medium',
        'choices': [
            {'text': '10', 'is_correct': False,
             'explanation': 'Wrong. With the `global` declaration, assignment to `x` rebinds the MODULE-level `x`, not a local.'},
            {'text': '20', 'is_correct': True,
             'explanation': 'Correct. `global x` tells Python that assignment to `x` inside `f` refers to the module-level name. After `f()` runs, the global `x` is 20.'},
            {'text': 'NameError', 'is_correct': False,
             'explanation': 'Wrong. `global` pairs with an existing or new name at module scope. The statement is valid.'},
            {'text': 'None', 'is_correct': False,
             'explanation': 'Wrong. `x` was assigned 20 via the global declaration.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def counter():\n    count = 0\n    def bump():\n        count = count + 1\n        return count\n    return bump\n\nc = counter()\nprint(c())",
        'difficulty': 'hard',
        'choices': [
            {'text': '1', 'is_correct': False,
             'explanation': 'Wrong. This would require `nonlocal count` inside `bump`. Without it, `count = count + 1` tries to read a LOCAL `count` that has not been assigned yet, raising UnboundLocalError.'},
            {'text': 'UnboundLocalError', 'is_correct': True,
             'explanation': 'Correct. Because `count` is ASSIGNED inside `bump`, Python treats it as a local variable throughout the function. `count + 1` then tries to READ the local before it\'s defined, raising `UnboundLocalError`. The fix is `nonlocal count`.'},
            {'text': '0', 'is_correct': False,
             'explanation': 'Wrong. No such fallback occurs. Read-before-write on a local name is an error.'},
            {'text': 'NameError', 'is_correct': False,
             'explanation': 'Wrong. The specific error is `UnboundLocalError` (a subclass of NameError), raised at the moment `count` is read.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def fact(n):\n    if n <= 1:\n        return 1\n    return n * fact(n - 1)\n\nprint(fact(5))",
        'difficulty': 'medium',
        'choices': [
            {'text': '120', 'is_correct': True,
             'explanation': 'Correct. Factorial: 5! = 5 × 4 × 3 × 2 × 1 = 120. Base case at n ≤ 1 returns 1 and unwinds the recursion.'},
            {'text': '15', 'is_correct': False,
             'explanation': 'Wrong. 15 = 1+2+3+4+5 (summation). Factorial multiplies.'},
            {'text': '25', 'is_correct': False,
             'explanation': 'Wrong. 25 = 5². Factorial is a cumulative product, not a square.'},
            {'text': 'RecursionError', 'is_correct': False,
             'explanation': 'Wrong. The base case `n <= 1` terminates the recursion. RecursionError would occur only without a proper base case.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "sq = lambda x: x * x\nprint(sq(4))",
        'difficulty': 'easy',
        'choices': [
            {'text': '16', 'is_correct': True,
             'explanation': 'Correct. `lambda x: x * x` is an anonymous function taking `x` and returning `x*x`. Called with 4, it returns 16.'},
            {'text': '4', 'is_correct': False,
             'explanation': 'Wrong. The lambda body is `x * x`, not `x`.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `lambda` is valid Python syntax for anonymous single-expression functions.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `int * int` is valid multiplication.'},
        ],
    },
    {
        'text': 'What does this function return?',
        'code_snippet': "def f(x):\n    if x > 0:\n        return 'positive'\n\nprint(f(-5))",
        'difficulty': 'easy',
        'choices': [
            {'text': 'None', 'is_correct': True,
             'explanation': 'Correct. If a function reaches the end of its body without a `return`, it implicitly returns `None`. Here `x > 0` is False, no `return` executes, so `None` is returned and printed.'},
            {'text': 'negative', 'is_correct': False,
             'explanation': 'Wrong. There is no `else` branch — the function doesn\'t return a different string for negatives; it just falls off the end.'},
            {'text': 'positive', 'is_correct': False,
             'explanation': 'Wrong. The `if` condition is False (−5 > 0 is False), so the `return \'positive\'` does not execute.'},
            {'text': 'Nothing', 'is_correct': False,
             'explanation': 'Wrong. `print(f(-5))` will always print SOMETHING — and since the function returns `None`, it prints `None`.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def total(*nums):\n    return sum(nums)\n\nprint(total(1, 2, 3, 4))",
        'difficulty': 'medium',
        'choices': [
            {'text': '10', 'is_correct': True,
             'explanation': 'Correct. `*nums` collects all positional arguments into a tuple `(1, 2, 3, 4)`. `sum((1,2,3,4))` = 10.'},
            {'text': '4', 'is_correct': False,
             'explanation': 'Wrong. That\'s the count of arguments. The function returns their `sum`.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `*args` packs any number of positional arguments into a tuple — it\'s designed for variadic calls.'},
            {'text': '[1, 2, 3, 4]', 'is_correct': False,
             'explanation': 'Wrong on two counts: the function returns `sum(nums)` (an int), not `nums`; and `*nums` creates a tuple, not a list.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def info(**kwargs):\n    return kwargs.get('role', 'unknown')\n\nprint(info(name='Alex', role='dev'))",
        'difficulty': 'medium',
        'choices': [
            {'text': 'dev', 'is_correct': True,
             'explanation': 'Correct. `**kwargs` collects keyword arguments into a dict `{\'name\': \'Alex\', \'role\': \'dev\'}`. `.get(\'role\', \'unknown\')` returns `\'dev\'`.'},
            {'text': 'unknown', 'is_correct': False,
             'explanation': 'Wrong. `\'role\'` IS in the kwargs dict, so `get` returns its value, not the default.'},
            {'text': 'Alex', 'is_correct': False,
             'explanation': 'Wrong. `get(\'role\', ...)` looks up the key `\'role\'`, not `\'name\'`.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `**kwargs` is the standard way to capture keyword arguments.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "try:\n    x = 10 / 0\nexcept ZeroDivisionError:\n    print('div by zero')\nexcept Exception:\n    print('other')",
        'difficulty': 'easy',
        'choices': [
            {'text': 'div by zero', 'is_correct': True,
             'explanation': 'Correct. `10 / 0` raises `ZeroDivisionError`. Python checks `except` clauses in order; the first match handles it and the rest are skipped.'},
            {'text': 'other', 'is_correct': False,
             'explanation': 'Wrong. The more specific `ZeroDivisionError` comes first and matches, so the general `Exception` handler does not run.'},
            {'text': 'div by zero\\nother', 'is_correct': False,
             'explanation': 'Wrong. Only ONE except clause runs per exception — the first match.'},
            {'text': 'Nothing (unhandled)', 'is_correct': False,
             'explanation': 'Wrong. `ZeroDivisionError` IS handled by the first except.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "try:\n    print('A')\n    raise ValueError('bad')\n    print('B')\nexcept ValueError:\n    print('C')\nfinally:\n    print('D')",
        'difficulty': 'medium',
        'choices': [
            {'text': 'A C D', 'is_correct': True,
             'explanation': 'Correct. `A` prints, then `raise` jumps to the except clause (so `B` is skipped). `C` prints from the handler. `D` prints from `finally`, which runs ALWAYS — whether or not an exception was raised.'},
            {'text': 'A B C D', 'is_correct': False,
             'explanation': 'Wrong. `raise` immediately stops normal flow, so `B` never prints.'},
            {'text': 'A C', 'is_correct': False,
             'explanation': 'Wrong. `finally` ALWAYS runs — even after a handled exception.'},
            {'text': 'A D', 'is_correct': False,
             'explanation': 'Wrong. The `except ValueError` matches the raised exception, so `C` also prints.'},
        ],
    },
    {
        'text': 'What exception does this raise?',
        'code_snippet': "lst = [1, 2, 3]\nprint(lst[10])",
        'difficulty': 'easy',
        'choices': [
            {'text': 'IndexError', 'is_correct': True,
             'explanation': 'Correct. Out-of-range INDEX access on a sequence (list, tuple, string) raises `IndexError`.'},
            {'text': 'KeyError', 'is_correct': False,
             'explanation': 'Wrong. `KeyError` is for DICTIONARIES when looking up a missing key. Lists use integer indices and raise `IndexError`.'},
            {'text': 'ValueError', 'is_correct': False,
             'explanation': 'Wrong. `ValueError` means an argument has a valid type but an inappropriate value. Out-of-range indexing is specifically `IndexError`.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `TypeError` would fire for an invalid index TYPE, e.g. `lst[\'a\']`. An int index out of range is `IndexError`.'},
        ],
    },
    {
        'text': 'What exception does this raise?',
        'code_snippet': "d = {'a': 1}\nprint(d['x'])",
        'difficulty': 'easy',
        'choices': [
            {'text': 'KeyError', 'is_correct': True,
             'explanation': 'Correct. Accessing a missing key in a dict via `d[key]` raises `KeyError`. To avoid it, use `d.get(key)` which returns `None` (or a default).'},
            {'text': 'IndexError', 'is_correct': False,
             'explanation': 'Wrong. `IndexError` is for SEQUENCES (lists/tuples/strings) accessed by integer index. Dicts raise `KeyError`.'},
            {'text': 'ValueError', 'is_correct': False,
             'explanation': 'Wrong. Missing keys specifically raise `KeyError`.'},
            {'text': 'None', 'is_correct': False,
             'explanation': 'Wrong. `d[missing_key]` raises an exception; it does NOT silently return `None`. Use `d.get(...)` for that behavior.'},
        ],
    },
    {
        'text': 'What exception does this raise?',
        'code_snippet': "print(int('abc'))",
        'difficulty': 'easy',
        'choices': [
            {'text': 'ValueError', 'is_correct': True,
             'explanation': 'Correct. `int(s)` raises `ValueError` when `s` is a string that cannot be parsed as an integer. The argument has the right type (str) but an inappropriate value.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. `TypeError` would fire for a wrong TYPE, e.g. `int([1,2,3])`. A str that simply cannot be parsed is `ValueError`.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `SyntaxError` is a compile-time error in source code. Runtime parsing failures are `ValueError`.'},
            {'text': 'NameError', 'is_correct': False,
             'explanation': 'Wrong. `NameError` is raised when a name is not found in any scope.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def f(lst=[]):\n    lst.append(1)\n    return lst\n\nprint(f())\nprint(f())",
        'difficulty': 'hard',
        'choices': [
            {'text': '[1]\\n[1]', 'is_correct': False,
             'explanation': 'Wrong. This is the classic mutable-default-argument pitfall. The default list is created ONCE at function-definition time and reused across calls.'},
            {'text': '[1]\\n[1, 1]', 'is_correct': True,
             'explanation': 'Correct. `def f(lst=[])` evaluates the default `[]` ONCE when the function is defined. That same list object is reused on every call where `lst` is not provided. So mutations persist: call 1 appends to produce `[1]`, call 2 appends to the SAME list, giving `[1, 1]`. Safer idiom: use `None` as the default and build a fresh list inside.'},
            {'text': 'TypeError', 'is_correct': False,
             'explanation': 'Wrong. The code runs without error — though it behaves surprisingly.'},
            {'text': '[]\\n[]', 'is_correct': False,
             'explanation': 'Wrong. `append(1)` always adds an element. Both calls must return a non-empty list.'},
        ],
    },
    {
        'text': 'What does this print?',
        'code_snippet': "def outer():\n    x = 1\n    def inner():\n        nonlocal x\n        x += 10\n    inner()\n    return x\n\nprint(outer())",
        'difficulty': 'hard',
        'choices': [
            {'text': '1', 'is_correct': False,
             'explanation': 'Wrong. `nonlocal x` binds the inner `x` to the enclosing `outer` scope. The `x += 10` thus mutates `outer`\'s `x`.'},
            {'text': '11', 'is_correct': True,
             'explanation': 'Correct. `nonlocal x` tells `inner` that `x` refers to the nearest enclosing (non-global) scope, which is `outer`. `x += 10` updates that `x` from 1 to 11. `outer` then returns 11.'},
            {'text': 'UnboundLocalError', 'is_correct': False,
             'explanation': 'Wrong. `nonlocal` resolves the scoping issue that would otherwise cause this error.'},
            {'text': 'SyntaxError', 'is_correct': False,
             'explanation': 'Wrong. `nonlocal` is a keyword (Python 3) specifically for this purpose.'},
        ],
    },
]

# ---------------------------------------------------------------------------

ALL_QUESTIONS = MODULE_1 + MODULE_2 + MODULE_3 + MODULE_4
